apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pigallery2
  name: pigallery2
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: pigallery2
  type: NodePort
status:
  loadBalancer: {}
