apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pigallery2
  name: pigallery2
spec:
  containers:
  - image: bpatrik/pigallery2:1.8.2
    name: pigallery2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
