apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pigallery2
  name: pigallery2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pigallery2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pigallery2
    spec:
      containers:
      - image: bpatrik/pigallery2:1.8.2
        name: pigallery2
        resources: {}
status: {}


---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pigallery2
  name: pigallery2
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: pigallery2
  type: NodePort
status:
  loadBalancer: {}

